// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlxmdwmqlchjosmzhvan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpseG1kd21xbGNoam9zbXpodmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwODQwNDYsImV4cCI6MjA5OTY2MDA0Nn0.ZCFXicJX6NmW0Psxfs9Pae6gay0diD0R_MRnIYumips";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});